
import { GameEntity } from './types';

// Fallback data in case API fails or for initial load
export const FALLBACK_ENTITIES: GameEntity[] = [
  { id: '1', name: 'Sparrow', translation: 'चिड़िया', canFly: true, emoji: '🐦' },
  { id: '2', name: 'Parrot', translation: 'तोता', canFly: true, emoji: '🦜' },
  { id: '3', name: 'Cow', translation: 'गाय', canFly: false, emoji: '🐄' },
  { id: '4', name: 'Airplane', translation: 'प्लेन', canFly: true, emoji: '✈️' }, // Colloquial for Airplane
  { id: '5', name: 'Elephant', translation: 'हाथी', canFly: false, emoji: '🐘' },
  { id: '6', name: 'Crow', translation: 'कौवा', canFly: true, emoji: '🐦‍⬛' },
  { id: '7', name: 'Cat', translation: 'बिल्ली', canFly: false, emoji: '🐱' },
  { id: '8', name: 'Buffalo', translation: 'भैंस', canFly: false, emoji: '🐃' },
  { id: '9', name: 'Eagle', translation: 'चील', canFly: true, emoji: '🦅' },
  { id: '10', name: 'Bus', translation: 'बस', canFly: false, emoji: '🚌' },
  { id: '11', name: 'Butterfly', translation: 'तितली', canFly: true, emoji: '🦋' },
  { id: '12', name: 'Table', translation: 'टेबल', canFly: false, emoji: '🪵' }, // Colloquial for Table
  { id: '13', name: 'Helicopter', translation: 'हेलीकॉप्टर', canFly: true, emoji: '🚁' },
  { id: '14', name: 'Dog', translation: 'कुत्ता', canFly: false, emoji: '🐕' },
  { id: '15', name: 'Rocket', translation: 'रॉकेट', canFly: true, emoji: '🚀' },
  { id: '16', name: 'Mosquito', translation: 'मच्छर', canFly: true, emoji: '🦟' },
  { id: '17', name: 'Chair', translation: 'कुर्सी', canFly: false, emoji: '🪑' },
  { id: '18', name: 'Bat', translation: 'चमगादड़', canFly: true, emoji: '🦇' },
  { id: '19', name: 'Monkey', translation: 'बंदर', canFly: false, emoji: '🐒' },
  { id: '20', name: 'Peacock', translation: 'मोर', canFly: true, emoji: '🦚' },
  // New Items
  { id: '21', name: 'Owl', translation: 'उल्लू', canFly: true, emoji: '🦉' },
  { id: '22', name: 'Lion', translation: 'शेर', canFly: false, emoji: '🦁' },
  { id: '23', name: 'Pigeon', translation: 'कबूतर', canFly: true, emoji: '🐦' },
  { id: '24', name: 'Car', translation: 'गाड़ी', canFly: false, emoji: '🚗' },
  { id: '25', name: 'Bee', translation: 'मधुमक्खी', canFly: true, emoji: '🐝' },
  { id: '26', name: 'Tiger', translation: 'बाघ', canFly: false, emoji: '🐅' },
  { id: '27', name: 'Dragonfly', translation: 'व्याध पतंग', canFly: true, emoji: '蜻' },
  { id: '28', name: 'House', translation: 'घर', canFly: false, emoji: '🏠' },
  { id: '29', name: 'Kite', translation: 'पतंग', canFly: true, emoji: '🪁' },
  { id: '30', name: 'Tree', translation: 'पेड़', canFly: false, emoji: '🌳' },
  { id: '31', name: 'Vulture', translation: 'गिद्ध', canFly: true, emoji: '🦅' },
  { id: '32', name: 'Phone', translation: 'फोन', canFly: false, emoji: '📱' },
  { id: '33', name: 'Drone', translation: 'ड्रोन', canFly: true, emoji: '🛸' },
  { id: '34', name: 'Book', translation: 'किताब', canFly: false, emoji: '📖' },
  { id: '35', name: 'Flamingo', translation: 'राजहंस', canFly: true, emoji: '🦩' },
  { id: '36', name: 'Laptop', translation: 'लैपटॉप', canFly: false, emoji: '💻' },
  { id: '37', name: 'Swan', translation: 'हंस', canFly: true, emoji: '🦢' },
  { id: '38', name: 'Shoe', translation: 'जूता', canFly: false, emoji: '👟' },
  { id: '39', name: 'Kingfisher', translation: 'रामचिरैया', canFly: true, emoji: '🐦' },
  { id: '40', name: 'Bottle', translation: 'बोतल', canFly: false, emoji: '🍾' },
  { id: '41', name: 'Duck', translation: 'बतख', canFly: true, emoji: '🦆' },
  { id: '42', name: 'Pen', translation: 'पेन', canFly: false, emoji: '🖊️' },
  { id: '43', name: 'Seagull', translation: 'गंगा-चिल्ली', canFly: true, emoji: '🐦' },
  { id: '44', name: 'Bed', translation: 'बिस्तर', canFly: false, emoji: '🛏️' },
  { id: '45', name: 'Ladybug', translation: 'गुबरैला', canFly: true, emoji: '🐞' },
  { id: '46', name: 'Pizza', translation: 'पिज़्ज़ा', canFly: false, emoji: '🍕' },
  { id: '47', name: 'Firefly', translation: 'जुगनू', canFly: true, emoji: '🌟' },
  { id: '48', name: 'Train', translation: 'ट्रेन', canFly: false, emoji: '🚂' },
  { id: '49', name: 'Hawk', translation: 'बाज़', canFly: true, emoji: '🦅' },
  { id: '50', name: 'Ball', translation: 'गेंद', canFly: false, emoji: '⚽' },
  // Batch 2 (51-100)
  { id: '51', name: 'Ant', translation: 'चींटी', canFly: false, emoji: '🐜' },
  { id: '52', name: 'Cloud', translation: 'बादल', canFly: true, emoji: '☁️' }, // Floats/moves in sky
  { id: '53', name: 'Pencil', translation: 'पेंसिल', canFly: false, emoji: '✏️' },
  { id: '54', name: 'Parachute', translation: 'पैराशूट', canFly: true, emoji: '🪂' },
  { id: '55', name: 'Spoon', translation: 'चम्मच', canFly: false, emoji: '🥄' },
  { id: '56', name: 'Balloon', translation: 'गुब्बारा', canFly: true, emoji: '🎈' },
  { id: '57', name: 'Door', translation: 'दरवाजा', canFly: false, emoji: '🚪' },
  { id: '58', name: 'Bat (Cricket)', translation: 'बल्ला', canFly: false, emoji: '🏏' },
  { id: '59', name: 'Hummingbird', translation: 'गुंजन पक्षी', canFly: true, emoji: '🐦' },
  { id: '60', name: 'Flower', translation: 'फूल', canFly: false, emoji: '🌸' },
  { id: '61', name: 'Jet', translation: 'जेट', canFly: true, emoji: '✈️' },
  { id: '62', name: 'Key', translation: 'चाबी', canFly: false, emoji: '🔑' },
  { id: '63', name: 'UFO', translation: 'उड़न तश्तरी', canFly: true, emoji: '🛸' },
  { id: '64', name: 'Lock', translation: 'ताला', canFly: false, emoji: '🔒' },
  { id: '65', name: 'Wasp', translation: 'ततैया', canFly: true, emoji: '🐝' },
  { id: '66', name: 'Hammer', translation: 'हथौड़ा', canFly: false, emoji: '🔨' },
  { id: '67', name: 'Crane', translation: 'सारस', canFly: true, emoji: '🦢' },
  { id: '68', name: 'Bucket', translation: 'बाल्टी', canFly: false, emoji: '🪣' },
  { id: '69', name: 'Stork', translation: 'बगुला', canFly: true, emoji: '🦩' },
  { id: '70', name: 'Bicycle', translation: 'साइकिल', canFly: false, emoji: '🚲' },
  { id: '71', name: 'Moth', translation: 'पतंगा', canFly: true, emoji: '🦋' },
  { id: '72', name: 'Truck', translation: 'ट्रक', canFly: false, emoji: '🚚' },
  { id: '73', name: 'Grasshopper', translation: 'टिड्डा', canFly: true, emoji: '🦗' },
  { id: '74', name: 'Ship', translation: 'जहाज', canFly: false, emoji: '🚢' },
  { id: '75', name: 'Pelican', translation: 'पेलिकन', canFly: true, emoji: '🐦' },
  { id: '76', name: 'Boat', translation: 'नाव', canFly: false, emoji: '🛶' },
  { id: '77', name: 'Woodpecker', translation: 'कठफोड़वा', canFly: true, emoji: '🐦' },
  { id: '78', name: 'Apple', translation: 'सेब', canFly: false, emoji: '🍎' },
  { id: '79', name: 'Ostrich', translation: 'शुतुरमुर्ग', canFly: false, emoji: '🐦' }, // Bird but cannot fly
  { id: '80', name: 'Banana', translation: 'केला', canFly: false, emoji: '🍌' },
  { id: '81', name: 'Penguin', translation: 'पेंगुइन', canFly: false, emoji: '🐧' }, // Bird but cannot fly
  { id: '82', name: 'Grapes', translation: 'अंगूर', canFly: false, emoji: '🍇' },
  { id: '83', name: 'Kiwi Bird', translation: 'कीवी', canFly: false, emoji: '🐦' }, // Bird but cannot fly
  { id: '84', name: 'Mango', translation: 'आम', canFly: false, emoji: '🥭' },
  { id: '85', name: 'Seaplane', translation: 'सीप्लेन', canFly: true, emoji: '✈️' },
  { id: '86', name: 'Orange', translation: 'संतरा', canFly: false, emoji: '🍊' },
  { id: '87', name: 'Blimp', translation: 'हवाई पोत', canFly: true, emoji: '🎈' },
  { id: '88', name: 'Potato', translation: 'आलू', canFly: false, emoji: '🥔' },
  { id: '89', name: 'Space Shuttle', translation: 'अंतरिक्ष यान', canFly: true, emoji: '🚀' },
  { id: '90', name: 'Tomato', translation: 'टमाटर', canFly: false, emoji: '🍅' },
  { id: '91', name: 'Satellite', translation: 'उपग्रह', canFly: true, emoji: '🛰️' },
  { id: '92', name: 'Onion', translation: 'प्याज', canFly: false, emoji: '🧅' },
  { id: '93', name: 'Phoenix', translation: 'फीनिक्स', canFly: true, emoji: '🔥' },
  { id: '94', name: 'Carrot', translation: 'गाजर', canFly: false, emoji: '🥕' },
  { id: '95', name: 'Dragon', translation: 'ड्रैगन', canFly: true, emoji: '🐉' },
  { id: '96', name: 'Clock', translation: 'घड़ी', canFly: false, emoji: '⏰' },
  { id: '97', name: 'Pegasus', translation: 'पेगासस', canFly: true, emoji: '🐎' },
  { id: '98', name: 'Watch', translation: 'हाथ घड़ी', canFly: false, emoji: '⌚' },
  { id: '99', name: 'Griffin', translation: 'ग्रिफिन', canFly: true, emoji: '🦅' },
  { id: '100', name: 'Glasses', translation: 'चश्मा', canFly: false, emoji: '👓' },
  // Batch 3 (101-150)
  { id: '101', name: 'Cup', translation: 'कप', canFly: false, emoji: '☕' },
  { id: '102', name: 'Hot Air Balloon', translation: 'गर्म हवा का गुब्बारा', canFly: true, emoji: '🎈' },
  { id: '103', name: 'Plate', translation: 'थाली', canFly: false, emoji: '🍽️' },
  { id: '104', name: 'Paper Plane', translation: 'कागज का विमान', canFly: true, emoji: '📄' },
  { id: '105', name: 'Fork', translation: 'कांटा', canFly: false, emoji: '🍴' },
  { id: '106', name: 'Frisbee', translation: 'फ्लाइंग डिस्क', canFly: true, emoji: '🥏' },
  { id: '107', name: 'Knife', translation: 'चाकू', canFly: false, emoji: '🔪' },
  { id: '108', name: 'Boomerang', translation: 'बूमरैंग', canFly: true, emoji: '🪃' },
  { id: '109', name: 'Television', translation: 'टीवी', canFly: false, emoji: '📺' },
  { id: '110', name: 'Arrow', translation: 'तीर', canFly: true, emoji: '🏹' },
  { id: '111', name: 'Radio', translation: 'रेडियो', canFly: false, emoji: '📻' },
  { id: '112', name: 'Bullet', translation: 'गोली', canFly: true, emoji: '🔫' },
  { id: '113', name: 'Computer', translation: 'कंप्यूटर', canFly: false, emoji: '🖥️' },
  { id: '114', name: 'Missile', translation: 'मिसाइल', canFly: true, emoji: '🚀' },
  { id: '115', name: 'Mouse (PC)', translation: 'माउस', canFly: false, emoji: '🖱️' },
  { id: '116', name: 'Comet', translation: 'धूमकेतु', canFly: true, emoji: '☄️' },
  { id: '117', name: 'Keyboard', translation: 'कीबोर्ड', canFly: false, emoji: '⌨️' },
  { id: '118', name: 'Meteor', translation: 'उल्का', canFly: true, emoji: '🌠' },
  { id: '119', name: 'Printer', translation: 'प्रिंटर', canFly: false, emoji: '🖨️' },
  { id: '120', name: 'Fairy', translation: 'परी', canFly: true, emoji: '🧚' },
  { id: '121', name: 'Camera', translation: 'कैमरा', canFly: false, emoji: '📷' },
  { id: '122', name: 'Angel', translation: 'फरिश्ता', canFly: true, emoji: '👼' },
  { id: '123', name: 'Bag', translation: 'बस्ता', canFly: false, emoji: '🎒' },
  { id: '124', name: 'Ghost', translation: 'भूत', canFly: true, emoji: '👻' }, // Often depicted floating/flying
  { id: '125', name: 'Hat', translation: 'टोपी', canFly: false, emoji: '🧢' },
  { id: '126', name: 'Witch', translation: 'चुड़ैल', canFly: true, emoji: '🧙‍♀️' }, // On broomstick
  { id: '127', name: 'Shirt', translation: 'कमीज', canFly: false, emoji: '👕' },
  { id: '128', name: 'Genie', translation: 'जिन', canFly: true, emoji: '🧞' }, // Floats
  { id: '129', name: 'Pants', translation: 'पतलून', canFly: false, emoji: '👖' },
  { id: '130', name: 'Superman', translation: 'सुपरमैन', canFly: true, emoji: '🦸' },
  { id: '131', name: 'Dress', translation: 'पोशाक', canFly: false, emoji: '👗' },
  { id: '132', name: 'Santa Claus', translation: 'सांता क्लॉज़', canFly: true, emoji: '🎅' }, // In sleigh
  { id: '133', name: 'Sock', translation: 'मोजा', canFly: false, emoji: '🧦' },
  { id: '134', name: 'Cupid', translation: 'कामदेव', canFly: true, emoji: '💘' },
  { id: '135', name: 'Ring', translation: 'अंगूठी', canFly: false, emoji: '💍' },
  { id: '136', name: 'Vampire Bat', translation: 'चमगादड़', canFly: true, emoji: '🦇' },
  { id: '137', name: 'Necklace', translation: 'हार', canFly: false, emoji: '📿' },
  { id: '138', name: 'Flying Fish', translation: 'उड़न मछली', canFly: true, emoji: '🐟' }, // Glides
  { id: '139', name: 'Umbrella', translation: 'छाता', canFly: false, emoji: '☂️' },
  { id: '140', name: 'Flying Squirrel', translation: 'उड़न गिलहरी', canFly: true, emoji: '🐿️' }, // Glides
  { id: '141', name: 'Wallet', translation: 'बटुआ', canFly: false, emoji: '👛' },
  { id: '142', name: 'Pterodactyl', translation: 'टेरोसॉर', canFly: true, emoji: '🦕' },
  { id: '143', name: 'Coin', translation: 'सिक्का', canFly: false, emoji: '🪙' },
  { id: '144', name: 'Robin', translation: 'रॉबिन', canFly: true, emoji: '🐦' },
  { id: '145', name: 'Credit Card', translation: 'क्रेडिट कार्ड', canFly: false, emoji: '💳' },
  { id: '146', name: 'Blue Jay', translation: 'नीलकंठ', canFly: true, emoji: '🐦' },
  { id: '147', name: 'Dollar', translation: 'डॉलर', canFly: false, emoji: '💵' },
  { id: '148', name: 'Cardinal', translation: 'कार्डिनल', canFly: true, emoji: '🐦' },
  { id: '149', name: 'Gold', translation: 'सोना', canFly: false, emoji: '🥇' },
  { id: '150', name: 'Finch', translation: 'फिंच', canFly: true, emoji: '🐦' },
];

export const INITIAL_SPEED = 1400; 
export const MIN_SPEED = 500; 
export const SPEED_DECREMENT = 150; 
export const MAX_LIVES = 3;